version: "3.9"
services:
  fastapi:
    build: ./fastapi
    container_name: fastapi_container
    ports:
      - "6677:6677"
  nextjs:
    build: ./nextjs
    container_name: nextjs_container
    ports:
      - "3000:3000"
